### ISSUE TITLE
How to confirm if it actually a valid _px2 cookie?

### ISSUE THREAD

**Issue by GameHackerPM** [jonathanyly/pxvaluesgen#2]
Hello! Thanks for the info, but how can we confirm it _px2 cookie is obtained valid or not? Is there a way other than performing the request to see if it will pass or not?

Also if you have discord or something need to contact you.

Thanks.

**Comment by jonathanyly** [comment]
Hello,
there is no way to see just by the cookie itself if its valid or not. You need to do the request to check if its passing.
However to create a px cookie you need to do two requests to the px endpoint to obtain a px3 cookie.

**Comment by GameHackerPM** [comment]
The site I'm using is px2 not px3, but having issues to know if it valid or not, as when I do the gen for the first 2 requests it gets the _px2 (bake) cookie, when I use it, it doesn't work for like 30-60 seconds, then the same cookie works after on that website, it's really sneaky and weird how it works on that site, other sites I tried was just either the gen is working fine so it passes or it doesn't work as the gen is not right! For the site I'm trying to do is hard to understand.

Do you think adding more requests like for fingerprints and mouse movement will make it even better? I would like to have some tips if you know.

**Comment by jonathanyly** [comment]
Generally PX does more requests after the first two to generate a px cookie. Doing those requests often improve the cookie. But I have never really worked on _px2 sites.
